Answerly/Answerly/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('questions.urls', namespace= 'questions')),
    path('tutor/', include('tutor.urls', namespace='tutor'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Answerly/questions/urls.py
from django.contrib import admin
from django.urls import path

from .views import (home, createQuestion, updateQuestion, deleteQuestion, 
registerUser, logoutUser, loginUser, createEvent, updateEvent, deleteEvent, listEvents, listQuestions, question, event, userProfile, profile)


app_name = 'questions'
urlpatterns = [
    path('', home, name='home'),
    path('register/', registerUser, name = 'register'),
    path('profile/<str:pk>', userProfile, name = 'profile'),
    path('logout/', logoutUser, name = 'logout'),
    path('login/', loginUser, name = 'login'),

    
    path('create-question/', createQuestion, name='create-question' ),
    path('update-question/<str:pk>', updateQuestion, name='update-question' ),
    path('delete-question/<str:pk>', deleteQuestion, name='delete-question' ),
    path('create-event/', createEvent, name = 'create-event'),
    path('update-event/<str:pk>', updateEvent, name = 'update-event'),
    path('delete-event/<str:pk>', deleteEvent, name = 'delete-event'),
    path('event-list/', listEvents, name='list-events'),
    path('question-list/', listQuestions, name='list-questions'),
    path('question/<str:pk>', question, name = 'question'),
    path('event/<str:pk>', event, name = 'event'),
    path('profile-update/', profile, name='update-profile')
] 

Answerly/tutor/urls.py
from django.contrib import admin
from django.urls import path
from .views import createTutor, findTutor, createMessage, displayMessages

app_name = 'tutor'
urlpatterns = [
    path('create/', createTutor, name = 'create-tutor'),
    path('find/', findTutor, name='find-tutor'),
    path('create-message/', createMessage, name='create-message'),
    path('display-messages/<str:pk>', displayMessages, name ='display-messages')
   
]

Answerly/questions/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import datetime
from django.utils.timezone import utc
# Create your models here.




class Question(models.Model):
    class Subject(models.TextChoices):
        MATH = 'Math'
        SCIENCE = 'Science'
        SOCIAL_STUDIES = 'Social Studies'
        ELA = 'Ela'

    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=200)
    subject = models.CharField(max_length=20, choices = Subject.choices, null=False, blank=False )
    description = models.TextField(null=True, blank=True)
    participants = models.ManyToManyField(User, related_name='participants', blank=True)
    updated = models.DateTimeField(auto_now=True)
    image = models.ImageField(default='default.jpg', upload_to='question_images', blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

class Response(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.body[0:30]

class Event(models.Model):
    title = models.CharField(max_length=200)
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    description = models.TextField(null=True, blank=True)
    date = models.DateField(default=datetime.date.today)
    location = models.CharField(max_length=200)


    def __str__(self):
        return self.title

class EventResponse(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, null=True)
    attending = models.BooleanField(null=True, blank=True)
    notattending = models.BooleanField(null=True, blank=True)

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'
    

Answerly/questions/forms.py
from django.forms import ModelForm
from .models import Question, Event, Profile
from django import forms
from django.contrib.auth.models import User


class QuestionForm(ModelForm):
    class Meta:
        model = Question
        fields = '__all__'
        exclude = ['author', 'participants', 'created']


class EventForm(ModelForm):
    class Meta:
        model = Event
        fields = "__all__"
        widgets = {
            'date': forms.widgets.DateInput(attrs={'type': 'date'})
        }
        exclude = ['host']

class UserUpdateForm(ModelForm):
    class Meta:
        model = User
        fields = ['username']


class ImageUpdateForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

Answerly/questions/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .models import Question, Event, Response, EventResponse
from .forms import QuestionForm, EventForm, UserUpdateForm, ImageUpdateForm
from django.db.models import Q
from django.contrib import messages
from django.contrib.auth.models import User
# Create your views here.

def home(request):
    return render(request, 'questions/home.html')

@login_required(login_url='login')
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        i_form = ImageUpdateForm(request.POST, request.FILES, instance=request.user.profile)

        if u_form.is_valid() and i_form.is_valid():
            u_form.save()
            i_form.save()
            messages.success(request, 'Your account has been updated!')
            return redirect('questions:home')
    else:
        u_form = UserUpdateForm(instance=request.user)
        i_form = ImageUpdateForm(instance=request.user.profile)


    context = {
        'u_form': u_form,
        'i_form': i_form
    }

    return render(request, 'questions/update_profile.html', context)



def userProfile(request, pk):
    user = User.objects.get(id=pk)
    questions = user.question_set.all()
    events = user.event_set.all()
    questionResponses = user.response_set.all()
    eventResponses = user.eventresponse_set.all()
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    if q == 'questions':
        context = {
            'user': user,
            'questions': questions,
            'events': events,
            'responses': questionResponses,
            'eresponses': eventResponses,
            'type': 'questions'
        }
        return render(request, 'questions/profile.html', context)
    elif q == 'events':
        context = {
            'user': user,
            'questions': questions,
            'events': events,
            'responses': questionResponses,
            'eresponses': eventResponses,
            'type': 'events'
        }
        return render(request, 'questions/profile.html', context)
    else:
        context = {
            'user': user,
            'questions': questions,
            'events': events,
            'responses': questionResponses,
            'eresponses': eventResponses,
        }
        return render(request, 'questions/profile.html', context)

def listQuestions(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    questions = Question.objects.filter(
        Q(subject__icontains = q) |
        Q(title__icontains = q) |
        Q(description__icontains = q)
        ).order_by('-created')

    count = Question.objects.count()
    responses = Response.objects.filter(Q(question__subject__icontains = q))

    context = {
        'questions': questions,
        'questions_count': count,
        'responses': responses
    }

    return render(request, 'questions/questions_list.html', context)

def listEvents(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    e = request.GET.get('e') if request.GET.get('e') != None else ''
    count = Event.objects.count()
    responses = EventResponse.objects.filter(attending = True)

    
    if q == 'newest':
        events = Event.objects.filter(
            Q(title__icontains = e) |
            Q(description__icontains = e)
        ).order_by('-date')


        context = {
            'events': events,
            'event_count': count,
            'eresponses': responses
        }

        return render(request, 'questions/events_list.html', context)
    else:
        events = Event.objects.filter(
            Q(title__icontains = e) |
            Q(description__icontains = e)
        ).order_by('-date')
        context = {
            'events': events,
            'event_count': count,
            'eresponses': responses
        }

        return render(request, 'questions/events_list.html', context)



def question(request, pk):
    question = Question.objects.get(id = pk)
    question_responses = question.response_set.all().order_by('created')
    participants = question.participants.all()

    if request.method == 'POST':
        response = Response.objects.create(
            user = request.user,
            question = question,
            body = request.POST.get('response'),
        )
        question.participants.add(request.user)
        return redirect('questions:question', question.id)


    return render(request, 'questions/question.html', {'question': question, 'responses': question_responses, 'participants': participants})


def event(request, pk):
    event = Event.objects.get(id = pk)
    responses = EventResponse.objects.filter(event = event)
    attendees = responses.filter(attending = True)

    if request.method == 'POST':
        if EventResponse.objects.filter(user=request.user, event = event).exists():
            messages.error(request, 'You already submitted a response!')
            return redirect('questions:event', event.id)
            
        else:
            eventresponse = EventResponse.objects.create(
                user = request.user,
                event = event,
                attending = request.POST.get('attending'),
                notattending = request.POST.get('notattending')
            )
        return redirect('questions:event', event.id)

    return render(request, 'questions/event.html', {'event': event, 'attendees': attendees})



@login_required(login_url='questions:login')
def createQuestion(request):
    form = QuestionForm()


    if request.method == 'POST':
        form = QuestionForm(request.POST, request.FILES)
        if form.is_valid():
            question = form.save(commit = False)
            question.author = request.user
            question.save()

            return redirect('questions:list-questions')

    context = {
        'form' : form,

    }


    return render(request, 'questions/create_question.html', context)

@login_required(login_url="questions:login")
def updateQuestion(request, pk):
    question = Question.objects.get(id=pk)
    form = QuestionForm(instance = question)

    if request.method == 'POST':
        form = QuestionForm(request.POST, instance = question)
        if form.is_valid():
            form.save()
            return redirect('questions:list-questions')

    context = {
        'form': form
    }

    return render(request, 'questions/create_question.html', context)

@login_required(login_url="questions:login")
def deleteQuestion(request, pk):
    question = Question.objects.get(id=pk)

    if request.method == 'POST':
        question.delete()
        return redirect('questions:list-questions')
    
    context = {
        'question': question
    }

    return render(request, 'questions/delete_question.html', context)

@login_required(login_url='questions:login')
def createEvent(request):
    form = EventForm()

    if request.method == 'POST':
        form = EventForm(request.POST)
        if form.is_valid():
            event = form.save(commit=False)
            event.host = request.user
            event.save()
            return redirect('questions:list-events')

    context = {
        'form' : form
    }

    return render(request, 'questions/create_event.html', context)


def updateEvent(request, pk):
    event = Event.objects.get(id = pk)
    form = EventForm(instance = event)


    if request.method == 'POST':
        form = EventForm(request.POST, instance = event)
        if form.is_valid():
            form.save()
            return redirect('questions:list-events')
    
    context = {
        'form': form
    }

    return render(request, 'questions/create_event.html', context)


def deleteEvent(request, pk):
    event = Event.objects.get(id = pk)
    if request.method == 'POST':
        event.delete()
        return redirect('questions:list-events')
    
    context = {
        'event': event
    }

    return render(request, 'questions/delete_event.html', context)



def registerUser(request):
    form = UserCreationForm()

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            login(request, user)
            return redirect('questions:home')
        else:
            messages.error(request, 'An error occured when logging in!')

    context = {
        'form': form,
        'page': 'register'
    }    

    return render(request, 'questions/login_register.html', context)

def logoutUser(request):
    if request.method == 'POST':
        logout(request)
        return redirect('questions:home')

    return render(request, 'questions/logout.html')

def loginUser(request):

    if request.user.is_authenticated:
        return redirect('questions:home')


    if request.method == 'POST':
        username = request.POST.get('username').lower()
        password = request.POST.get('password')

        try:
            user = User.objects.get(username = username) 
        except:
            messages.error(request, 'User does not exist')
            
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('questions:home')
        else:
            messages.error(request, "User name or password does not exist")


    
    return render(request, 'questions/login_register.html')

Answerly/questions/templates/questions/activity_component.html
<h2>Recent Activity</h2>
<hr>
{% for message in responses %}
    <div class="media-body">
        <h5><a href="{% url 'questions:profile' message.user.id %}">@{{ message.user }}</a> {{ message.created|timesince }}</h5>
        <h5>replied to <a href="{% url 'questions:question' message.question.id %}">"{{ message.question }}"</a></h5>
        <p>{{ message }}</p>
        <hr>
    </div>
{% endfor %}

Answerly/questions/templates/questions/create_event.html
{% extends 'main.html' %}

{% block content %}

<div>
    <center>
        <form method="POST" action="">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Submit">
        </form>
    </center>
</div>

{% endblock content %}

Answerly/questions/templates/questions/create_question.html
{% extends 'main.html' %}
{% block content %}


<div>
    <center>
        <form method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}

            <input type="submit" value="Submit">
        </form>
    </center>
</div>

{% endblock content %}

Answerly/questions/templates/questions/create_room.html
{% extends 'main.html' %}

{% block content %}

<div>
    <form method="POST" action="">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit">
    </form>
</div>

{% endblock content %}

Answerly/questions/templates/questions/delete_question.html
{% extends 'main.html' %}

{% block content %}

<div>
    <form method="POST" action="">
        {% csrf_token %}
        <h1>Are you sure you want to delete  "{{ question.title }}"</h1>
        <input type="submit" value="Delete">
    </form>
</div>

{% endblock content %}

Answerly/questions/templates/questions/event_feed.html
{% for event in events %}
    <article class = "media content-section">
            <div>
                <img class="account-img" style="border-radius: 50%; width: 50px; height: 50px;" src = "{{ event.host.profile.image.url }}">
                <p><a href="{% url 'questions:profile' event.host.id %}">@{{event.host.username}}</a></p>
                {% if request.user == event.host %}
                <a href="{% url 'questions:update-event' event.id %}">Edit Event | </a>
                <a href="{% url 'questions:delete-event' event.id %}">Delete Event | </a>
                {% endif %}
                <h3><a href="{% url 'questions:event' event.id %}">{{ event.title }}</a></h3>
                <small>{{ event.date }}</small>      
            </div>
    </article>
{% endfor %}

Answerly/questions/templates/questions/events_component.html
{% for message in eresponses %}
    <div >
        <h5><a href="{% url 'questions:profile' message.user.id %}">@{{ message.user }}</a></h5>
        <h5>will be attending <a href="{% url 'questions:event' message.event.id %}">"{{ message.event }}"</a></h5>
        <hr>
    </div>
{% endfor %}

Answerly/questions/templates/questions/home.html
{% extends 'main.html' %}

{% block content %}

<article class="media content-section">
    <div class="media-body">
      <center><h1>
          {% if request.user.is_authenticated %}
            Welcome to Answerly, {{request.user.username}}!
          {% else %}
            Welcome to Answerly!
          {% endif %}
        </h1></center>
    </div>
  </article>

  <article class="media content-section">
    <div class="media-body">
      <center><h2><a class = 'article-title 'href="{% url 'questions:list-questions' %}">Explore Questions</a></h2></center>
    </div>
    <div>
        <center><p class="article-content">Explore our multitude of questions. Ask for help, or help those in need!</p></center>
    </div>
  </article>

  <article class="media content-section">
    <div class="media-body">
      <center><h2><a class = 'article-title 'href="{% url 'questions:list-events' %}">Explore Events</a></h2></center>
    </div>
    <div>
        <center><p class="article-content">Get involved by joining or starting your own events. Whether it be community fundraisers or club meetings!</p></center>
    </div>
  </article>

  <article class="media content-section">
    <div class="media-body">
      <center><h2>Explore Our Tutoring Services!</h2></center><br>
      <center><a href="{% url 'tutor:create-tutor' %}">Become a tutor today!</a></center><br>
      <center><a href="{% url 'tutor:find-tutor' %}">Find a tutor today!</a></center>
    </div>
  </article>
  
{% endblock content%}

Answerly/questions/templates/questions/login_register.html
{% extends 'main.html' %}


{% block content %}

{% if page == 'register' %}

<div class="log">
    <h1>Sign up for answerly</h1>
    <h2>Get help with any subject</h2>
    <form method="POST" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register">
    </form>
</div>

{% else %}

<div class="log">
    <h1>Welcome back</h1>
    <h2>Sign in to your account</h2>
    <form method="POST" action="">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" id="username" name = "username" placeholder = "Enter your username"></input>
        <label for="password">Password:</label>
        <input type="password" id="password" name = "password" placeholder = "Enter your password"></input>
        <input type="submit" value="Login">
        Dont have an account? <a href="{% url 'questions:register' %}">Sign up here!</a>
    </form>
</div>
{% endif %}

{% endblock content %}

Answerly/questions/templates/questions/logout.html
{% extends 'main.html' %}

{% block content %}

<div>
    <center>
    <form method="POST" action="">
            {% csrf_token %}
            <h1>Are you sure you want to logout? </h1>
            <input type="submit" value="logout">
            
        </form>
        <a class="small" href = "{% url 'questions:home' %}">Home</a>
    </center>
</div>

{% endblock content %}

Answerly/questions/templates/questions/profile.html
{% extends 'main.html' %}

{% block content %}

<style>
    .profile-container{
        display: grid;
        grid-template-columns: 1fr 3fr 1fr;
    }
</style>

<div>
    <center><img class="account-img" style="border-radius: 50%;" src = "{{ user.profile.image.url }}"></center>
</div>
<div>
    <center><h1>{{ user.username }}</h1></center>
    <center><a href = "{% url 'questions:update-profile'%}">Update Profile</a></center><br>
</div>

<div class = "profile-container">
    <div class="browse">
        <a href="{% url 'questions:profile' user.id %}?q=questions">Questions</a>
        <a href="{% url 'questions:profile' user.id %}?q=events">Events</a>
        <a href="{% url 'questions:profile' user.id %}">All</a>
    </div>
    
    <div>
        {% if type == 'questions' %}
            {% include 'questions/feed_component.html'%}
        
        {% elif type == 'events' %}
            {% include 'questions/event_feed.html'%}
        {% else %}
            {% include 'questions/feed_component.html'%}
            {% include 'questions/event_feed.html'%}
        {% endif %}
    </div>

    <div>
        {% include 'questions/activity_component.html' %}
        {% include 'questions/events_component.html' %}
    </div>
</div>

{% endblock content%}

Answerly/questions/templates/questions/question.html
{% extends 'main.html' %}

{% block content %}

<div class="room-container">
    <div class="media content-section">
    <h1>{{question.title}}</h1>

    <small>{{ question.created }}</small>

    <p>{{ question.description }}</p>

    {% if question.image != 'default.jpg' %}
        <img style="width: 300px; height: 300px;"src="{{question.image.url}}">
    {% endif %}

    <div class="comment-wrapper">
        <h3>Conversation</h3>
        <hr>

        {% for response in responses %}
            <div>
            <small>@{{response.user.username}} {{response.created|timesince}}</small>
            <p>{{response.body}}</p>
            <hr>
            </div>
            {% endfor %}
        </div>

        {% if request.user.is_authenticated %}
            <div class="comment-form">
                <form method="POST" action="">
                    {% csrf_token %}
                    <input type="text" name="response" placeholder="message here">
                </form>
            </div>
        {% endif %}
    </div>
    <div>
        <h2>Participants</h2>
        <hr>

        {% for user in participants %}
            <div>
                <h2>@{{user.username}}</h2>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}

Answerly/questions/templates/questions/questions_list.html
{% extends 'main.html' %}

{% block content %}

<div class="home-container">
    <div class="media-body">
        <h2>Browse Questions</h2>
        <div class="browse">
            <a href="{% url 'questions:list-questions' %}?q=Math">Math</a>
            <a href="{% url 'questions:list-questions' %}?q=Ela">Ela</a>
            <a href="{% url 'questions:list-questions' %}?q=Science">Science</a>
            <a href="{% url 'questions:list-questions' %}?q=Social Studies">Social Studies</a>
            <a href="{% url 'questions:list-questions' %}">All Questions</a>
        </div>
    </div>
    <div>
        <div class="home-header">
            <h3>{{questions_count}} questions</h3>
            <form method="GET" action="">
                {% csrf_token %}
                <center><input type="text" name="q" placeholder="Search Questions..."></center>
            </form>
            <a class="btn btn-outline-info mb-4" href="{% url 'questions:create-question' %}">Ask a Question</a></center>
            
        </div>
        {% include 'questions/feed_component.html' %}
    </div>

    <div>
        {% include 'questions/activity_component.html' %}
    </div>

</div>

{% endblock content %}

Answerly/questions/templates/questions/update_profile.html
{% extends 'main.html' %}

{% block content %}

<div>
    <h1>Update Profile</h1>
    <div class="log">
        <form method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{ u_form.as_p }}
            {{ i_form.as_p }}
            <input type="submit" value="Update">
        </form>
    </div>
</div>

{% endblock content %}