Answerly/Answerly/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('questions.urls', namespace= 'questions')),
    path('tutor/', include('tutor.urls', namespace='tutor'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Answerly/questions/urls.py
from django.contrib import admin
from django.urls import path

from .views import (home, createQuestion, updateQuestion, deleteQuestion, 
registerUser, logoutUser, loginUser, createEvent, updateEvent, deleteEvent, listEvents, listQuestions, question, event, userProfile, profile)


app_name = 'questions'
urlpatterns = [
    path('', home, name='home'),
    path('register/', registerUser, name = 'register'),
    path('profile/<str:pk>', userProfile, name = 'profile'),
    path('logout/', logoutUser, name = 'logout'),
    path('login/', loginUser, name = 'login'),

    
    path('create-question/', createQuestion, name='create-question' ),
    path('update-question/<str:pk>', updateQuestion, name='update-question' ),
    path('delete-question/<str:pk>', deleteQuestion, name='delete-question' ),
    path('create-event/', createEvent, name = 'create-event'),
    path('update-event/<str:pk>', updateEvent, name = 'update-event'),
    path('delete-event/<str:pk>', deleteEvent, name = 'delete-event'),
    path('event-list/', listEvents, name='list-events'),
    path('question-list/', listQuestions, name='list-questions'),
    path('question/<str:pk>', question, name = 'question'),
    path('event/<str:pk>', event, name = 'event'),
    path('profile-update/', profile, name='update-profile')
] 

Answerly/tutor/urls.py
from django.contrib import admin
from django.urls import path
from .views import createTutor, findTutor, createMessage, displayMessages

app_name = 'tutor'
urlpatterns = [
    path('create/', createTutor, name = 'create-tutor'),
    path('find/', findTutor, name='find-tutor'),
    path('create-message/', createMessage, name='create-message'),
    path('display-messages/<str:pk>', displayMessages, name ='display-messages')
   
]

Answerly/templates/main.html
{% load static %}


<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel = 'stylesheet' type = 'text/css' media="screen" href="{% static 'styles/main.css' %}">
    <title>Answerly</title>
</head>
<body>
    {% include 'navbar.html' %}
    <div class="wrapper">
        {% block content %}
        {% endblock content %}
    </div>
</body>
</html>

Answerly/templates/navbar.html
{% if request.user.is_authenticated %}
  <nav class="topnav">
      <a  href="{% url 'questions:home' %}">answerly.</a>
      <a href="{% url 'questions:profile' request.user.id %}">Profile</a>
      <a href="{% url 'tutor:display-messages' request.user.id %}">Messages</a>
      <a href="{% url 'questions:logout' %}">Logout</a>
  </nav>
{% else %}
  <nav class="topnav">
      <a href="{% url 'questions:home' %}">answerly.</a>
      <a href="{% url 'questions:login' %}">Login</a>
  </nav>
{% endif %}