Answerly/Answerly/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('questions.urls', namespace= 'questions')),
    path('tutor/', include('tutor.urls', namespace='tutor'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Answerly/questions/urls.py
from django.contrib import admin
from django.urls import path

from .views import (home, createQuestion, updateQuestion, deleteQuestion, 
registerUser, logoutUser, loginUser, createEvent, updateEvent, deleteEvent, listEvents, listQuestions, question, event, userProfile, profile)


app_name = 'questions'
urlpatterns = [
    path('', home, name='home'),
    path('register/', registerUser, name = 'register'),
    path('profile/<str:pk>', userProfile, name = 'profile'),
    path('logout/', logoutUser, name = 'logout'),
    path('login/', loginUser, name = 'login'),

    
    path('create-question/', createQuestion, name='create-question' ),
    path('update-question/<str:pk>', updateQuestion, name='update-question' ),
    path('delete-question/<str:pk>', deleteQuestion, name='delete-question' ),
    path('create-event/', createEvent, name = 'create-event'),
    path('update-event/<str:pk>', updateEvent, name = 'update-event'),
    path('delete-event/<str:pk>', deleteEvent, name = 'delete-event'),
    path('event-list/', listEvents, name='list-events'),
    path('question-list/', listQuestions, name='list-questions'),
    path('question/<str:pk>', question, name = 'question'),
    path('event/<str:pk>', event, name = 'event'),
    path('profile-update/', profile, name='update-profile')
] 

Answerly/tutor/urls.py
from django.contrib import admin
from django.urls import path
from .views import createTutor, findTutor, createMessage, displayMessages

app_name = 'tutor'
urlpatterns = [
    path('create/', createTutor, name = 'create-tutor'),
    path('find/', findTutor, name='find-tutor'),
    path('create-message/', createMessage, name='create-message'),
    path('display-messages/<str:pk>', displayMessages, name ='display-messages')
   
]

Answerly/tutor/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Tutor(models.Model):
    class Subject(models.TextChoices):
        MATH = 'Math'
        SCIENCE = 'Science'
        SOCIAL_STUDIES = 'Social Studies'
        ELA = 'Ela'

    class Levels(models.TextChoices):
        ELEMENTARY = 'Elementary'
        MIDDLE = 'Middle'
        HIGH = 'High'
        COLLEGE = 'College'

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=100)
    bio = models.TextField()
    subject = models.CharField(max_length=20, choices = Subject.choices, null=False, blank=False)
    level = models.CharField(max_length=20, choices = Levels.choices, null=False, blank=False)
    email = models.EmailField(max_length=100)

class Message(models.Model):
    recipient = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=200)
    body = models.TextField()
    sent = models.DateTimeField(auto_now_add=True)
    sender = models.CharField(max_length=100)

Answerly/tutor/forms.py
from django.forms import ModelForm
from .models import Tutor, Message


class TutorForm(ModelForm):
    class Meta:
        model = Tutor
        fields = "__all__"
        exclude = ['user']

class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = "__all__"
        exclude = ['sender']

Answerly/tutor/views.py
from django.shortcuts import render, redirect
from .forms import TutorForm, MessageForm
from django.http import HttpResponseRedirect
from .models import Tutor, Message
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls import reverse
# Create your views here.

@login_required(login_url='questions:login')
def createTutor(request):
    form = TutorForm()


    if request.method == 'POST':
        form = TutorForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.user = request.user
            form.save()
            return HttpResponseRedirect(reverse('questions:home'))
        
    context = {
        'form': form
    }
        
    return render(request, 'tutor/tutor_signup.html', context)


@login_required(login_url='questions:login')
def findTutor(request):
    if request.method == 'POST':
        course = request.POST.get('subject')
        lvl = request.POST.get('level')

        tutors = Tutor.objects.all()
        potential_tutors = tutors.filter(subject = course)
        tutor = potential_tutors.filter(level = lvl)

        context = {
            'type': 'tutor',
            'tutors': tutor
        }

        return render(request, 'tutor/find_tutor.html', context)

        
    context = {
        'type': 'search'
    }
    return render(request, 'tutor/find_tutor.html', context)



@login_required(login_url='questions:login')
def createMessage(request):
    form = MessageForm()

    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.sender = request.user.username
            form.save()

            return HttpResponseRedirect(reverse('questions:home'))
        
    context = {
        'form': form
    }
    return render(request, 'tutor/create_message.html', context)


def displayMessages(request, pk):
    messages = Message.objects.all()

    context = {
        'messages': messages.filter(recipient=request.user).order_by('-sent')
    }

    return render(request, 'tutor/list_messages.html', context)

Answerly/tutor/templates/tutor/create_message.html
{% extends 'main.html' %}

{% block content %}


<div>
    <center>
        <h1>Send a Message</h1><br>
        <form method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Send">
        </form>
    </center>
</div>

{% endblock content %}

Answerly/tutor/templates/tutor/find_tutor.html
{% extends 'main.html' %}

{% block content %}

{% if type == 'search' %}
    <center>
        <div>
            <form method="POST" action="" enctype="multipart/form-data">
                {% csrf_token %}
                <h1>Find a Tutor</h1>
                <input type="text" style="width: 215px;" name="class" placeholder="What class do you need help with?">
                <br>
                <h2>What subject do you need help in?</h2>
                <select name="subject">
                    <option value="Math">Math</option>
                    <option value="Ela">ELA</option>
                    <option value="Science">Science</option>
                    <option value="Social Studies">Social Studies</option>
                </select>
                <br>
                <br>
                <h2>At what level do you need help with?</h2>
                <select name="level">
                    <option value="Elementary">Elementary School</option>
                    <option value="Middle">Middle School</option>
                    <option value="High">High School</option>
                    <option value="College">College</option>
                </select>

                <br>
                <input type="submit" value="Sign Up">
            </form>
        </div>
    </center>
{% else %}
    <center><h1>POTENTIAL TUTORS</h1></center>
    {% for tutor in tutors %}
        <center>
            <article class="media content-section">
                <div class = "media-body">
                    <h1>{{tutor.name}}</small><br>
                    <small style="font-size: 10px;"><a href="{% url 'questions:profile' tutor.user.id %}">@{{tutor.user.username}}</a></small>
                    <h5>{{tutor.subject}} Tutor</h5>
                    <h5>{{ tutor.email }}</small><br><br>
                    <small>{{tutor.bio}}</small>
                    <hr>            
                    <a href="{% url 'tutor:create-message' %}">Send a message</a>
                </div>
            </article>
        </center>
    {% endfor %}


{% endif %}

{% endblock content %}

Answerly/tutor/templates/tutor/list_messages.html
{% extends 'main.html' %}

{% block content %}

<center>
    <center><h1>Your Messages</h1></center>
    <center><small><a href="{% url 'tutor:create-message' %}">Send a message</a></small></center><br>
    <article class="media content-section">
        <div class = "media-body">
            {% for message in messages %}   
                <h1>{{message.title}}</h1>
                
                <h5>{{ message.sender }}</h5>
                <small>{{ message.body }}</small><br><br>
                <small>{{message.sent}}</small><br><br>
                <small><a href="{% url 'tutor:create-message' %}">Respond Back</a></small>
                <hr>

            {% endfor %}         
        </div>
    </article>
</center>

{% endblock content %}

Answerly/tutor/templates/tutor/tutor_signup.html
{% extends 'main.html' %}

{% block content %}

<div>
    <center>
        <form method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Sign Up">
        </form>
    </center>
</div>

{% endblock content %}